version: "3.8"

services:
  ml-api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ml-api-container
    ports:
      - "3021:3021"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:3021/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Opcional: montar logs para persistir fora do container
      - ./logs:/app/logs
    networks:
      - ml-network

networks:
  ml-network:
    driver: bridge

# Opcional: Volume para persistir dados se necessário
volumes:
  ml-data:
    driver: local
